# StellarAnchorUK <stellaranchoruk.xyz>
VERSION="2.2.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GBOL57VCIN2FU6DRFETSXWADI4BC4A52KGETCX7MH6YSHYI2QI2UNOOD"
]

[DOCUMENTATION]
ORG_NAME="Gavitoken"
ORG_URL="https://gavitoken.github.io"
ORG_LOGO = "https://gavitoken.github.io/img/gavi.png"
ORG_OFFICIAL_EMAIL="gavitoken@gmail.com"
ORG_SUPPORT_EMAIL="gavitoken@gmail.com"
ORG_TWITTER="0xgavitoken"
ORG_DESCRIPTION="Gavitoken: Create Value to Crypto Space"
[[PRINCIPALS]]
email="gavitoken@gmail.com"

[[CURRENCIES]]
code = "GAVI"
name = "GAVI"
issuer = "GBOL57VCIN2FU6DRFETSXWADI4BC4A52KGETCX7MH6YSHYI2QI2UNOOD"
is_asset_anchored=false
display_decimals = 7
desc="GAVI is a crypto token. It represents a tradable asset that resides on Stellar blockchain and allows the holder to use it for investment."
image="https://gavitoken.github.io/img/gavi.png"
conditions="There will only ever be 1 billion GAVI tokens in existence."
status="live"
anchor_asset_type="other"
redemption_instructions="Redeemable through the KRWC/yUSDC trading pair on the SDEX."
name="KRW Coin"
desc="KRWC is a mirror representation of the South Korean Won on the Stellar network. Using the Stellar DEX, we keep KRWC pegged to the same value as the current market rates of real world KRW & USD. KRWC allows users of Stellar to hold a representation on the South Korean Won within the ecosystem. Each token is backed by a USDC reserve, which is verifiable by viewing our issuing wallet on the network. We ensure to always have enough USDC in reserve to buy back all issued KRWC through the SDEX. A minimum spread of 1.25% is set by the issuing wallet on buy & sell offers, with offers updated regularly to reflect other market prices. Visit us at https://stellaranchoruk.xyz"
image="https://stellaranchoruk.xyz/images/tokens/KRWC.png"
