# Gavitoken <gavitoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBOL57VCIN2FU6DRFETSXWADI4BC4A52KGETCX7MH6YSHYI2QI2UNOOD"
]

[DOCUMENTATION]
ORG_NAME="Gavitoken"
ORG_URL="https://gavitoken.github.io"
ORG_LOGO = "https://gavitoken.github.io/img/gavi.png"
ORG_OFFICIAL_EMAIL="gavitoken@gmail.com"
ORG_SUPPORT_EMAIL="gavitoken@gmail.com"
ORG_TWITTER="0xgavitoken"
ORG_DESCRIPTION="Gavitoken: Create Value to Crypto Space"

[[CURRENCIES]]
code = "GAVI"
name = "GAVI"
issuer = "GBOL57VCIN2FU6DRFETSXWADI4BC4A52KGETCX7MH6YSHYI2QI2UNOOD"
is_asset_anchored=false
anchor_asset_type = ""
display_decimals = 7
desc="GAVI is a crypto token. It represents a tradable asset that resides on Stellar blockchain and allows the holder to use it for investment."
image="https://gavitoken.github.io/img/gavi.png"
conditions="There will only ever be 1 billion GAVI tokens in existence."
status="live"
fixed_number=1000000000
